### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by thelindat** [overextended/ox_core#109]
- add group types (e.g. police, gang) to easily prevent joining groups with the same type
- change the duty/service system
- helper functions
- group accounts (was handled by pefcl, and may keep a compatibility layer?)
- player group functions (getGroup, hasGroup, etc.) - possibly breaking changes?
- enhanced permission system? something synced with clients would be useful too
- should we handle grades in the db similarly to esx?

**Comment by CoachYT1** [comment]
I think it would be useful if external scripts could register jobs and grades without having to add them in the database

**Comment by thelindat** [comment]
Groups are used in the database for data integrity so they need to exist regardless of a script registering them during runtime.

**Comment by Justus-Braun** [comment]
I am trying to create a service, but I came to wonder.

In the OxPlayer class, we have groups.
In the OxGroup class, we have members.

I think there should be only one of these.

I guess it would make more sense to have the groups in the OxPlayer class because you will be trying to get the group of the player more often than getting all the players from a group.
